version: '3.8'

services:
  frontend:
    container_name: evelin
    build:
      context: .
      target: runner  # указываем, что нужно использовать стадию runner для сборки
    ports:
      - "3001:3001"  # пробрасываем порт, чтобы приложение было доступно снаружи
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=0.0.0.0
    user: "1001"  # используем созданного пользователя для запуска


volumes:
  .next_cache:  # объявляем volume, если вы хотите сохранить кэш .next между перезапусками контейнера
